# Generated by Django 5.1.4 on 2025-01-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_endereco_alter_paciente_historico_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('conteudo', models.TextField(verbose_name='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento:'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historico_medico',
            field=models.TextField(max_length=500, verbose_name='Histórico médico:'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome:'),
        ),
    ]
